fix serialization for Optional type
After https://github.com/lovasoa/marshmallow_dataclass/pull/100, the
serialization works correctly, however the deserialization can fail.

eg
```
class Dclass:
  value: Optional[Union[int, str]]
```

If we load `{"value": None}` we correctly have `Dclass(value=None)`, but
serializing back this value will give an error

```
TypeError: Unable to serialize value with any of the fields in the union:
[TypeError('type of value must be int; got NoneType instead'), TypeError('type
of value must be str; got NoneType instead')]
```

The idea of this patch is to accept None when required=False